var express = require('express');
var app = express();

json = {
 "1% Milk": 90,
 "Apple Jacks": 76,
 "Apple Juice": 90,
 "Apple Sauce": -59,
 "Artichoke Hearts": -46,
 "Baby Carrots": 63,
 "Balsamic Vinaigrette Dressing": 96,
 "Balsamic Vinegar Dressing Fat Free": -53,
 "Bartlett Pears": 86,
 "Beer Battered Onion Rings": -43,
 "Belgian Waffles": 53,
 "Blue Cheese Dressing": -12,
 "Broccoli Florettes": -2,
 "Brocolli, Cauliflour & Carrots": 83,
 "Butterscotch Pudding": -94,
 "Cake Cone": 64,
 "Cap'N Crunch": 39,
 "Cauliflower Florettes": 49,
 "Celery Sticks": 59,
 "Cheerios": 27,
 "Cheese Pizza": 15,
 "Chipolte Mayo": -44,
 "Chocolate Low Fat Soft Serve Ice Cream": 0,
 "Chopped Romaine Lettuce": 60,
 "Chow Mein Noodles": -13,
 "Chunky Chicken Salad": -79,
 "Cinnamon Toast Crunch": -71,
 "Classic Greek Dressing": -59,
 "Club White Bread": 69,
 "Cold Elbow Macaroni": -19,
 "Corn Pops": 47,
 "Crackers": -60,
 "Cracklin Bran": 1,
 "Craisins": -80,
 "Cranberry Juice": -92,
 "Creamy Caesar Dressing": -95,
 "Cut Corn": -27,
 "Deli Sliced Corned Beef": -13,
 "Deli Sliced Roast Beef": -61,
 "Deli Sliced Turkey": 25,
 "Diet Soda": 72,
 "Dijon Mustard": 53,
 "Dijon Vinaigrette Dressing": -6,
 "Dill Pickle Spears": 93,
 "Egg Salad": -24,
 "English Muffins": -94,
 "Feta Cheese": -28,
 "Flaked Tuna": -83,
 "Fresh Bananas": -91,
 "Fresh Oranges": -97,
 "Fresh Sliced Mushrooms": -10,
 "Fresh Zucchini": -31,
 "Froot Loops": 33,
 "Frosted Flakes": 59,
 "Frosted Mini Wheats": -25,
 "Garbanzo Beans": -78,
 "Garlic & Chive Roasted Hummus": 4,
 "Gorilla Munch": -3,
 "Grape Jelly": 63,
 "Grape Juice": 2,
 "Grape Nuts": 76,
 "Grape Tomatoes": 53,
 "Grapefruit Sections": -65,
 "Grilled Cheeseburger": 43,
 "Grilled Chicken Breast": -12,
 "Grilled Hamburger": 68,
 "Hard Cooked Eggs": -90,
 "Hazelnut Spread": 68,
 "Honey": 64,
 "Honey Mustard Dressing": -87,
 "Hot Chocolate": 90,
 "Julienne Green Pepper": 50,
 "Kashi Good Friends Cereal": 11,
 "Ketchup": -92,
 "Kidney Beans": -24,
 "Lactaid Milk": -88,
 "Light Italian Dressing": -35,
 "Light Olive Oil Vinaigrette Dressing": -32,
 "LoFat Cottage Cheese": 20,
 "Lowfat Chocolate Milk": -56,
 "Lowfat Mayonnaise": -11,
 "Lucky Charms": 71,
 "Macintosh Apples": 87,
 "Marshmallow Fluff": 12,
 "Mayonnaise": 4,
 "Mesclun Spring Mix": 14,
 "Mild Yellow Shredded Cheddar": 33,
 "Mini Marshmallows": 60,
 "No Cholesterol Egg White": 76,
 "Olive Oil": 15,
 "Orange Juice": 33,
 "Orange Marmalade": -33,
 "Organic Hemp & Flax Granola": 50,
 "Organic LF Raspberry Granola": 12,
 "Organic Peanut Butter": -56,
 "PC Butter Reddies": -81,
 "Peanut Butter": 10,
 "Pepperoncini": 22,
 "Pesto Sauce": 75,
 "Pitted Black Olives": -75,
 "Plain Tofu": -58,
 "Raisin Bran": -43,
 "Raisins": 98,
 "Ranch Dressing": 73,
 "Raspberry Lime Vinaigrette": -29,
 "Regular Soda": 8,
 "Rice Milk": -2,
 "SB Crumbled Bleu Cheese": -53,
 "SB Organic Edamame": -10,
 "SB Vegan Asian Teriyaki Tofu": -27,
 "Seasoned Croutons": 95,
 "Shredded Carrots": 44,
 "Shredded Chicken": 45,
 "Silk Soy Chocolate Milk": -29,
 "Silk Soy Vanilla Milk": 70,
 "Skim Milk": -52,
 "Sliced Cucumbers 1/4\"": 35,
 "Sliced Mild Cheddar Cheese": 17,
 "Sliced Muenster Cheese": -6,
 "Sliced Pears": -17,
 "Sliced Provolone Cheese": -60,
 "Sliced Red Onions": 47,
 "Sliced Swiss Cheese": -81,
 "Smart Start": -87,
 "Soy Milk": -11,
 "Spinach": 16,
 "Strawberry Jelly": 32,
 "Sun Dried Tomato Dressing": -69,
 "Thick N Chunky Mild Salsa": -54,
 "Thousand Island Dressing": 62,
 "Tropical Fruit Salad": -10,
 "Tuna Salad": -42,
 "Ultimate Chocolate Cheese Cake": -9,
 "Unsalted Sunflower Seeds": 38,
 "Unsliced Italian Bread": 90,
 "VG Chickpea Vindaloo": 9,
 "VG Organic Black Beans": -32,
 "VG Organic Brown Rice": -99,
 "VG Quinoa & Spring Vegetable Pilaf": -64,
 "VG Split Pea Soup": 87,
 "VG Thai Burrito": -30,
 "VM Garden Burger": 62,
 "VM Scrambled Eggs": 37,
 "Vanilla Soft Serve": 95,
 "Vegan No Dairy Cheese Pizza": -47,
 "White Hamburger Roll": -93,
 "Whole Eggs": -1,
 "Whole Milk": -76,
 "Whole Wheat Bread": -92,
 "Whole Wheat Cheese Pizza": 80,
 "Whole Wheat English Muffin": 28,
 "Yellow American Cheese": 13,
 "Yellow Delicious Apples": -13
}

app.set('port', (process.env.PORT || 5000));
app.use(express.static(__dirname + '/public'));

app.get('/', function(request, response) {
  response.send(json);
});

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'));
});